import { Inter, Montserrat } from 'next/font/google';
import './globals.css';
import Header from './components/header';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-neutral-950 text-neutral-100`}>
        <div className="flex flex-col min-h-[100dvh]">
          <Header />
          <main className="flex-1 flex flex-col">
            <div className="container flex-1 flex flex-col">{children}</div>
          </main>
          <footer>789</footer>
        </div>
      </body>
    </html>
  );
}
